name: tw_calendar
description: simple custom calendar for your , support custom headerView, support modify widgets height...
version: 1.2.1
homepage: https://github.com/zeqinjie/tw_calendar

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


